version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: job_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Add your database connection string.
      # Using the Postgres service above: postgresql://postgres:postgres@db:5432/job_tracker_db
      DATABASE_URL: "your database connection string"
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_GRAPHQL_URL: http://localhost:4000/graphql
    restart: unless-stopped
    ports:
      - '5174:80'
    depends_on:
      - backend

volumes:
  pgdata:
